# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LandSubdivision
                                 A QGIS plugin
 This plugin subdivides a piece of land from blocks to parcels , adds Roads, and respects a riparian reserve
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-03
        copyright            : (C) 2023 by MGC Software Solutions
        email                : mulyungivick09@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LandSubdivision class from file LandSubdivision.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .land_subdivision import LandSubdivision
    return LandSubdivision(iface)
